config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :accommodations do
  	get :buy,  on: :member
  end
  root to: "accommodations#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/asset.rb
class Asset < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'owner_id'
  has_many :photos


  def files=(array_of_files = [])
    array_of_files.each do |f|
      photos.build(image: f, asset: self)
    end
  end
end

app/models/commecial_unit.rb
class CommecialUnit < Asset
end

app/models/complex_building.rb
class ComplexBuilding < Asset
end

app/models/house.rb
class House < Asset
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :asset
  has_attached_file :image
  do_not_validate_attachment_file_type :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable
  enum role: {admin: 0, owner: 1, customer: 2}

  has_many :assets
end

app/models/very_long_task.rb
class VeryLongTask
  # call this method when you have to perform the very long task
  def perform
    sleep 60
    true # the task was completed correctly
  end
end

app/controllers/accommodations_controller.rb
class AccommodationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_asset, only: [:buy, :show]

  def index
    @assets = Asset.all.order(created_at: :desc)
  end

  def new
    @asset = Asset.new
  end

  def create
    asset = Asset.new(asset_param)
    if asset.save
      redirect_to root_path, notice: ''
    else
      render 'new'
    end
  end

  def buy
    VeryLongTaskWorker.perform_async(@asset.id, current_user.id)
    redirect_to root_path
  end

  def show; end

  private

  def asset_param
    params.require(:asset).permit(:owner_id, :address, :type,
      :price, :sqmt, :rooms, :floors, :air_cond, :units, :parking, :shops, files: [])
  end

  def set_asset
    @asset = Asset.find_by(id: params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :role])
  end
end

app/helpers/accommodations_helper.rb
module AccommodationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accommodations/index.html.erb
<div class="row">
  <div class='col-md-12 '>
    <%= button_to "logout", destroy_user_session_path, method: :delete %>
  </div>
</div>

<div class="row">
  <div class='col-md-12'>
    <h3 class='col-md-6'>Assets Listing</h3>
    <%= link_to 'Add Asset', new_accommodation_path, class: 'btn btn-primary float-right', style: "margin: 10px;"%>
  </div>
</div>

<table  class="table">
  <thead>
    <tr>
      <th>Owner</th>
      <th>Address</th>
      <th>Type</th>
      <th>Sqmt</th>
      <th>Price</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @assets.each do |asset| %>
      <tr>
        <td><%= asset.user.name %></td>
        <td><%= asset.address %></td>
        <td><%= asset.type %></td>
        <td><%= asset.sqmt %></td>
        <td><%= asset.price %></td>
        <td><%= link_to "Show", accommodation_path(asset) %>
          <%= link_to "Buy", buy_accommodation_path(asset) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/accommodations/new.html.erb
<h1>Add Asset Item</h1>
<%= form_for(@asset, url: accommodations_path, method: :post) do |f| %>
  <div class="form-horizontal">
  	<div class="form-group">
      <%= f.label :type, class: "col-sm-2 control-label required" %>
      <div class="col-sm-7">
        <%= f.select :type,
                      options_for_select(
                        [['House', 'House'], ['CommecialUnit', 'CommecialUnit'], ['ComplexBuilding', 'ComplexBuilding'] ],
                        @asset.type
                        )
                %>
	    </div>     
	  </div>

  	<div class="form-group">
      <%= f.label :address, class: "col-sm-2 control-label required" %>
      <div class="col-sm-7">
        <%= f.text_field :address, class: "form-control" %>
      </div>
    </div>  

    <div class="form-group">
      <%= f.label :price, class: "col-sm-2 control-label required" %>
      <div class="col-sm-7">
        <%= f.text_field :price, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :sqmt, class: "col-sm-2 control-label required" %>
      <div class="col-sm-7">
        <%= f.text_field :sqmt, class: "form-control" %>
      </div>
    </div>

    <div class="house">
      <div class="form-group">
        <%= f.label :rooms, class: "col-sm-2 control-label required" %>
        <div class="col-sm-7">
          <%= f.select :rooms,  options_for_select(
                          [1,2,3,4,5],
                          @asset.rooms
                          ) %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :floors, class: "col-sm-2 control-label required" %>
        <div class="col-sm-7">
          <%= f.select :floors,  options_for_select(
                          [1,2,3,4,5],
                          @asset.floors
                          ) %>
  	    </div>     
  	  </div>
  	  <div class="form-group">
        <%= f.label :air_cond, class: "col-sm-2 control-label required" %>
        <div class="col-sm-7">
          <%= f.select :air_cond,
                        options_for_select(
                          [['No', false], ['Yes', true] ],
                          @asset.air_cond
                          )
                  %>
  	   </div>
  	  </div>     
    </div>

    <div class="complex-building">
      <div class="form-group">
        <%= f.label :units, class: "col-sm-2 control-label required" %>
        <div class="col-sm-7">
          <%= f.text_field :units, class: "form-control" %>
        </div>
      </div>     
    </div>
    
    <div class="commecial-unit" >
      <div class="form-group">
        <%= f.label :shops, class: "col-sm-2 control-label required" %>
        <div class="col-sm-7">
          <%= f.text_field :shops, class: "form-control" %>
        </div>   
      </div>

      <div class="form-group">
        <%= f.label :parking, class: "col-sm-2 control-label required" %>
        <div class="col-sm-7">
          <%= f.text_field :parking, class: "form-control" %>
        </div>
      </div>     
    </div>

    <div class="form-group">
      <%= f.label 'Image', class: "col-sm-2 control-label required" %>
      <div class="col-sm-7">
        <%= f.file_field :files, multiple: true %>
      </div>
    </div> 
    
	  <%= f.hidden_field :owner_id, value: current_user.id, class: "form-control" %>
    <div class="form-group">
      <%= link_to "Back", root_path %>
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/accommodations/show.html.erb
<div class="col-md-12">
	<h1>Show Asset</h1>
	<ul>
		<li><strong>Owner:</strong> <%= @asset.user.name %></li>
		<li><strong>Address:</strong> <%= @asset.address %></li>
		<li><strong>Sqmt:</strong> <%= @asset.sqmt %></li>
		<li><strong>Price:</strong> <%= @asset.price %></li>
		<% if @asset.type.eql?('House')%>
			<li><strong>Rooms:</strong> <%= @asset.rooms %></li>
			<li><strong>Floors:</strong> <%= @asset.floors %></li>
			<li><strong>AC:</strong> <%= @asset.air_cond ? 'Yes' : 'No' %></li>
		<% end %>
		<% if @asset.type.eql?('ComplexBuilding')%>
			<li><strong>Units:</strong> <%= @asset.units %></li>
		<% end %>
		<% if @asset.type.eql?('CommecialUnit')%>
			<li><strong>Shops:</strong> <%= @asset.shops %></li>
			<li><strong>Parking:</strong> <%= @asset.parking %></li>
		<% end%>
		<li><strong>Images:</strong>
			<% @asset.photos.each do |photo|  %>
		    <div>
		      <%= link_to photo.image.url do%>
		        <%= photo.image_file_name %>
		      <% end %>
		    </div>
		  <% end %>
		</li>
	</ul>
	<%= link_to "Back", root_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RealHouse</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>